module.exports = class Data1644523333089 {
  name = 'Data1644523333089'

  async up(db) {
    await db.query(`ALTER TABLE "contribution" DROP COLUMN "extrinisic_hash"`)
    await db.query(`ALTER TABLE "transfer" DROP COLUMN "extrinisic_hash"`)
    await db.query(`ALTER TABLE "reward" DROP COLUMN "extrinisic_hash"`)
    await db.query(`ALTER TABLE "crowdloan" ADD "status" character varying(9)`)
    await db.query(`ALTER TABLE "contribution" ADD "event_id" text`)
    await db.query(`ALTER TABLE "contribution" ADD "extrinsic_id" text`)
    await db.query(`ALTER TABLE "contribution" ADD "extrinsic_hash" text`)
    await db.query(`ALTER TABLE "transfer" ADD "event_id" text`)
    await db.query(`ALTER TABLE "transfer" ADD "extrinsic_id" text`)
    await db.query(`ALTER TABLE "transfer" ADD "extrinsic_hash" text`)
    await db.query(`ALTER TABLE "reward" ADD "event_id" text`)
    await db.query(`ALTER TABLE "reward" ADD "extrinsic_id" text`)
    await db.query(`ALTER TABLE "reward" ADD "extrinsic_hash" text`)
    await db.query(`ALTER TABLE "crowdloan" DROP COLUMN "contributors"`)
    await db.query(`ALTER TABLE "crowdloan" ADD "contributors" jsonb`)
    await db.query(`ALTER TABLE "contribution" DROP CONSTRAINT "FK_34a9b7747fbe547737724da5a3b"`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "date" DROP NOT NULL`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "block_number" DROP NOT NULL`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "success" DROP NOT NULL`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "account" DROP NOT NULL`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "amount" DROP NOT NULL`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "crowdloan_id" DROP NOT NULL`)
    await db.query(`ALTER TABLE "contribution" ADD CONSTRAINT "FK_34a9b7747fbe547737724da5a3b" FOREIGN KEY ("crowdloan_id") REFERENCES "crowdloan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
  }

  async down(db) {
    await db.query(`ALTER TABLE "contribution" ADD "extrinisic_hash" text`)
    await db.query(`ALTER TABLE "transfer" ADD "extrinisic_hash" text`)
    await db.query(`ALTER TABLE "reward" ADD "extrinisic_hash" text`)
    await db.query(`ALTER TABLE "crowdloan" DROP COLUMN "status"`)
    await db.query(`ALTER TABLE "contribution" DROP COLUMN "event_id"`)
    await db.query(`ALTER TABLE "contribution" DROP COLUMN "extrinsic_id"`)
    await db.query(`ALTER TABLE "contribution" DROP COLUMN "extrinsic_hash"`)
    await db.query(`ALTER TABLE "transfer" DROP COLUMN "event_id"`)
    await db.query(`ALTER TABLE "transfer" DROP COLUMN "extrinsic_id"`)
    await db.query(`ALTER TABLE "transfer" DROP COLUMN "extrinsic_hash"`)
    await db.query(`ALTER TABLE "reward" DROP COLUMN "event_id"`)
    await db.query(`ALTER TABLE "reward" DROP COLUMN "extrinsic_id"`)
    await db.query(`ALTER TABLE "reward" DROP COLUMN "extrinsic_hash"`)
    await db.query(`ALTER TABLE "crowdloan" ADD "contributors" text array`)
    await db.query(`ALTER TABLE "crowdloan" DROP COLUMN "contributors"`)
    await db.query(`ALTER TABLE "contribution" ADD CONSTRAINT "FK_34a9b7747fbe547737724da5a3b" FOREIGN KEY ("crowdloan_id") REFERENCES "crowdloan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "date" SET NOT NULL`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "block_number" SET NOT NULL`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "success" SET NOT NULL`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "account" SET NOT NULL`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "amount" SET NOT NULL`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "crowdloan_id" SET NOT NULL`)
    await db.query(`ALTER TABLE "contribution" DROP CONSTRAINT "FK_34a9b7747fbe547737724da5a3b"`)
  }
}
