module.exports = class Data1647611412709 {
  name = 'Data1647611412709'

  async up(db) {
    await db.query(`CREATE TABLE "contributor" ("id" character varying NOT NULL, "amount" numeric NOT NULL, "crowdloan_id" character varying NOT NULL, "account_id" character varying NOT NULL, CONSTRAINT "PK_816afef005b8100becacdeb6e58" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_d618ae1f4c3bf8e87d148be829" ON "contributor" ("crowdloan_id") `)
    await db.query(`CREATE INDEX "IDX_49a80f5ab8144c75a66632becf" ON "contributor" ("account_id") `)
    await db.query(`ALTER TABLE "crowdloan" DROP COLUMN "contributors"`)
    await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_0751309c66e97eac9ef11493623"`)
    await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496"`)
    await db.query(`ALTER TABLE "transfer" ALTER COLUMN "to_id" SET NOT NULL`)
    await db.query(`ALTER TABLE "transfer" ALTER COLUMN "from_id" SET NOT NULL`)
    await db.query(`ALTER TABLE "account_transfer" DROP CONSTRAINT "FK_d5240d17696e229585da974641a"`)
    await db.query(`ALTER TABLE "account_transfer" ALTER COLUMN "account_id" SET NOT NULL`)
    await db.query(`ALTER TABLE "contribution" DROP CONSTRAINT "FK_34a9b7747fbe547737724da5a3b"`)
    await db.query(`ALTER TABLE "contribution" DROP CONSTRAINT "FK_1e238c006392e74f87e2db5bf9b"`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "crowdloan_id" SET NOT NULL`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "account_id" SET NOT NULL`)
    await db.query(`ALTER TABLE "reward" DROP CONSTRAINT "FK_4a8843fdb7840bfd00f8e4f7b36"`)
    await db.query(`ALTER TABLE "reward" ALTER COLUMN "account_id" SET NOT NULL`)
    await db.query(`ALTER TABLE "slash" DROP CONSTRAINT "FK_11c194818d549fdd45eb5f4cbf4"`)
    await db.query(`ALTER TABLE "slash" ALTER COLUMN "account_id" SET NOT NULL`)
    await db.query(`ALTER TABLE "stake" DROP CONSTRAINT "FK_48a0a4f6ef7ee7a7395cdce1a2a"`)
    await db.query(`ALTER TABLE "stake" ALTER COLUMN "account_id" SET NOT NULL`)
    await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_0751309c66e97eac9ef11493623" FOREIGN KEY ("to_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496" FOREIGN KEY ("from_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "account_transfer" ADD CONSTRAINT "FK_d5240d17696e229585da974641a" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "contributor" ADD CONSTRAINT "FK_d618ae1f4c3bf8e87d148be8297" FOREIGN KEY ("crowdloan_id") REFERENCES "crowdloan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "contributor" ADD CONSTRAINT "FK_49a80f5ab8144c75a66632becf8" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "contribution" ADD CONSTRAINT "FK_34a9b7747fbe547737724da5a3b" FOREIGN KEY ("crowdloan_id") REFERENCES "crowdloan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "contribution" ADD CONSTRAINT "FK_1e238c006392e74f87e2db5bf9b" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "reward" ADD CONSTRAINT "FK_4a8843fdb7840bfd00f8e4f7b36" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "slash" ADD CONSTRAINT "FK_11c194818d549fdd45eb5f4cbf4" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "stake" ADD CONSTRAINT "FK_48a0a4f6ef7ee7a7395cdce1a2a" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
  }

  async down(db) {
    await db.query(`DROP TABLE "contributor"`)
    await db.query(`DROP INDEX "public"."IDX_d618ae1f4c3bf8e87d148be829"`)
    await db.query(`DROP INDEX "public"."IDX_49a80f5ab8144c75a66632becf"`)
    await db.query(`ALTER TABLE "crowdloan" ADD "contributors" jsonb`)
    await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_0751309c66e97eac9ef11493623" FOREIGN KEY ("to_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496" FOREIGN KEY ("from_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "transfer" ALTER COLUMN "to_id" DROP NOT NULL`)
    await db.query(`ALTER TABLE "transfer" ALTER COLUMN "from_id" DROP NOT NULL`)
    await db.query(`ALTER TABLE "account_transfer" ADD CONSTRAINT "FK_d5240d17696e229585da974641a" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "account_transfer" ALTER COLUMN "account_id" DROP NOT NULL`)
    await db.query(`ALTER TABLE "contribution" ADD CONSTRAINT "FK_34a9b7747fbe547737724da5a3b" FOREIGN KEY ("crowdloan_id") REFERENCES "crowdloan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "contribution" ADD CONSTRAINT "FK_1e238c006392e74f87e2db5bf9b" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "crowdloan_id" DROP NOT NULL`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "account_id" DROP NOT NULL`)
    await db.query(`ALTER TABLE "reward" ADD CONSTRAINT "FK_4a8843fdb7840bfd00f8e4f7b36" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "reward" ALTER COLUMN "account_id" DROP NOT NULL`)
    await db.query(`ALTER TABLE "slash" ADD CONSTRAINT "FK_11c194818d549fdd45eb5f4cbf4" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "slash" ALTER COLUMN "account_id" DROP NOT NULL`)
    await db.query(`ALTER TABLE "stake" ADD CONSTRAINT "FK_48a0a4f6ef7ee7a7395cdce1a2a" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "stake" ALTER COLUMN "account_id" DROP NOT NULL`)
    await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_0751309c66e97eac9ef11493623"`)
    await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496"`)
    await db.query(`ALTER TABLE "account_transfer" DROP CONSTRAINT "FK_d5240d17696e229585da974641a"`)
    await db.query(`ALTER TABLE "contributor" DROP CONSTRAINT "FK_d618ae1f4c3bf8e87d148be8297"`)
    await db.query(`ALTER TABLE "contributor" DROP CONSTRAINT "FK_49a80f5ab8144c75a66632becf8"`)
    await db.query(`ALTER TABLE "contribution" DROP CONSTRAINT "FK_34a9b7747fbe547737724da5a3b"`)
    await db.query(`ALTER TABLE "contribution" DROP CONSTRAINT "FK_1e238c006392e74f87e2db5bf9b"`)
    await db.query(`ALTER TABLE "reward" DROP CONSTRAINT "FK_4a8843fdb7840bfd00f8e4f7b36"`)
    await db.query(`ALTER TABLE "slash" DROP CONSTRAINT "FK_11c194818d549fdd45eb5f4cbf4"`)
    await db.query(`ALTER TABLE "stake" DROP CONSTRAINT "FK_48a0a4f6ef7ee7a7395cdce1a2a"`)
  }
}
