module.exports = class Data1647630683982 {
  name = 'Data1647630683982'

  async up(db) {
    await db.query(`DROP INDEX "public"."IDX_082fbbbbe6a84c865abaa72817"`)
    await db.query(`DROP INDEX "public"."IDX_c7f626a4ebde04b5e0c5b829a6"`)
    await db.query(`DROP INDEX "public"."IDX_9b160aadef096ecfb822596aaf"`)
    await db.query(`DROP INDEX "public"."IDX_a76ad44e5c4b11502f6116db54"`)
    await db.query(`DROP INDEX "public"."IDX_c6f769bd779f0ea56bf439d88e"`)
    await db.query(`DROP INDEX "public"."IDX_b0c42436fed4fb44e9cfc4a5e2"`)
    await db.query(`ALTER TABLE "transfer" RENAME COLUMN "chain_name" TO "chain_id"`)
    await db.query(`ALTER TABLE "crowdloan" RENAME COLUMN "chain_name" TO "chain_id"`)
    await db.query(`ALTER TABLE "contribution" RENAME COLUMN "chain_name" TO "chain_id"`)
    await db.query(`ALTER TABLE "reward" RENAME COLUMN "chain_name" TO "chain_id"`)
    await db.query(`ALTER TABLE "slash" RENAME COLUMN "chain_name" TO "chain_id"`)
    await db.query(`ALTER TABLE "stake" RENAME COLUMN "chain_name" TO "chain_id"`)
    await db.query(`CREATE TABLE "chain" ("id" character varying NOT NULL, "token" jsonb NOT NULL, CONSTRAINT "PK_8e273aafae283b886672c952ecd" PRIMARY KEY ("id"))`)
    await db.query(`ALTER TABLE "parachain" ADD "relay_chain_id" character varying`)
    await db.query(`ALTER TABLE "account" ADD "chain_id" character varying NOT NULL`)
    await db.query(`ALTER TABLE "transfer" DROP COLUMN "chain_id"`)
    await db.query(`ALTER TABLE "transfer" ADD "chain_id" character varying NOT NULL`)
    await db.query(`ALTER TABLE "parachain" ALTER COLUMN "name" SET NOT NULL`)
    await db.query(`ALTER TABLE "crowdloan" DROP COLUMN "chain_id"`)
    await db.query(`ALTER TABLE "crowdloan" ADD "chain_id" character varying NOT NULL`)
    await db.query(`ALTER TABLE "contribution" DROP COLUMN "chain_id"`)
    await db.query(`ALTER TABLE "contribution" ADD "chain_id" character varying NOT NULL`)
    await db.query(`ALTER TABLE "reward" DROP COLUMN "chain_id"`)
    await db.query(`ALTER TABLE "reward" ADD "chain_id" character varying NOT NULL`)
    await db.query(`ALTER TABLE "slash" DROP COLUMN "chain_id"`)
    await db.query(`ALTER TABLE "slash" ADD "chain_id" character varying NOT NULL`)
    await db.query(`ALTER TABLE "stake" DROP COLUMN "chain_id"`)
    await db.query(`ALTER TABLE "stake" ADD "chain_id" character varying NOT NULL`)
    await db.query(`CREATE INDEX "IDX_f1f1143749d9fd473890b77054" ON "transfer" ("chain_id") `)
    await db.query(`CREATE INDEX "IDX_115c699f0d08e6a3eb40e7b085" ON "parachain" ("relay_chain_id") `)
    await db.query(`CREATE INDEX "IDX_7ecfe931e23f88d1e45d5f658f" ON "crowdloan" ("chain_id") `)
    await db.query(`CREATE INDEX "IDX_7f50f702330bd90c3eb85bcbda" ON "contribution" ("chain_id") `)
    await db.query(`CREATE INDEX "IDX_4832b065968736dc04d37ca5da" ON "reward" ("chain_id") `)
    await db.query(`CREATE INDEX "IDX_7bdd91da49e79f51ebd8fb774c" ON "slash" ("chain_id") `)
    await db.query(`CREATE INDEX "IDX_30e9455c5aa944326797150a1b" ON "stake" ("chain_id") `)
    await db.query(`CREATE INDEX "IDX_6b15368424e1f5cf587c2f3c5a" ON "account" ("chain_id") `)
    await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_f1f1143749d9fd473890b77054b" FOREIGN KEY ("chain_id") REFERENCES "chain"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "parachain" ADD CONSTRAINT "FK_115c699f0d08e6a3eb40e7b085a" FOREIGN KEY ("relay_chain_id") REFERENCES "chain"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "crowdloan" ADD CONSTRAINT "FK_7ecfe931e23f88d1e45d5f658f1" FOREIGN KEY ("chain_id") REFERENCES "chain"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "contribution" ADD CONSTRAINT "FK_7f50f702330bd90c3eb85bcbda5" FOREIGN KEY ("chain_id") REFERENCES "chain"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "reward" ADD CONSTRAINT "FK_4832b065968736dc04d37ca5daf" FOREIGN KEY ("chain_id") REFERENCES "chain"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "slash" ADD CONSTRAINT "FK_7bdd91da49e79f51ebd8fb774cb" FOREIGN KEY ("chain_id") REFERENCES "chain"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "stake" ADD CONSTRAINT "FK_30e9455c5aa944326797150a1bb" FOREIGN KEY ("chain_id") REFERENCES "chain"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "account" ADD CONSTRAINT "FK_6b15368424e1f5cf587c2f3c5ac" FOREIGN KEY ("chain_id") REFERENCES "chain"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
  }

  async down(db) {
    await db.query(`CREATE INDEX "IDX_082fbbbbe6a84c865abaa72817" ON "transfer" ("chain_name") `)
    await db.query(`CREATE INDEX "IDX_c7f626a4ebde04b5e0c5b829a6" ON "crowdloan" ("chain_name") `)
    await db.query(`CREATE INDEX "IDX_9b160aadef096ecfb822596aaf" ON "contribution" ("chain_name") `)
    await db.query(`CREATE INDEX "IDX_a76ad44e5c4b11502f6116db54" ON "reward" ("chain_name") `)
    await db.query(`CREATE INDEX "IDX_c6f769bd779f0ea56bf439d88e" ON "slash" ("chain_name") `)
    await db.query(`CREATE INDEX "IDX_b0c42436fed4fb44e9cfc4a5e2" ON "stake" ("chain_name") `)
    await db.query(`ALTER TABLE "transfer" RENAME COLUMN "chain_id" TO "chain_name"`)
    await db.query(`ALTER TABLE "crowdloan" RENAME COLUMN "chain_id" TO "chain_name"`)
    await db.query(`ALTER TABLE "contribution" RENAME COLUMN "chain_id" TO "chain_name"`)
    await db.query(`ALTER TABLE "reward" RENAME COLUMN "chain_id" TO "chain_name"`)
    await db.query(`ALTER TABLE "slash" RENAME COLUMN "chain_id" TO "chain_name"`)
    await db.query(`ALTER TABLE "stake" RENAME COLUMN "chain_id" TO "chain_name"`)
    await db.query(`DROP TABLE "chain"`)
    await db.query(`ALTER TABLE "parachain" DROP COLUMN "relay_chain_id"`)
    await db.query(`ALTER TABLE "account" DROP COLUMN "chain_id"`)
    await db.query(`ALTER TABLE "transfer" ADD "chain_id" text`)
    await db.query(`ALTER TABLE "transfer" DROP COLUMN "chain_id"`)
    await db.query(`ALTER TABLE "parachain" ALTER COLUMN "name" DROP NOT NULL`)
    await db.query(`ALTER TABLE "crowdloan" ADD "chain_id" text NOT NULL`)
    await db.query(`ALTER TABLE "crowdloan" DROP COLUMN "chain_id"`)
    await db.query(`ALTER TABLE "contribution" ADD "chain_id" text NOT NULL`)
    await db.query(`ALTER TABLE "contribution" DROP COLUMN "chain_id"`)
    await db.query(`ALTER TABLE "reward" ADD "chain_id" text`)
    await db.query(`ALTER TABLE "reward" DROP COLUMN "chain_id"`)
    await db.query(`ALTER TABLE "slash" ADD "chain_id" text`)
    await db.query(`ALTER TABLE "slash" DROP COLUMN "chain_id"`)
    await db.query(`ALTER TABLE "stake" ADD "chain_id" text`)
    await db.query(`ALTER TABLE "stake" DROP COLUMN "chain_id"`)
    await db.query(`DROP INDEX "public"."IDX_f1f1143749d9fd473890b77054"`)
    await db.query(`DROP INDEX "public"."IDX_115c699f0d08e6a3eb40e7b085"`)
    await db.query(`DROP INDEX "public"."IDX_7ecfe931e23f88d1e45d5f658f"`)
    await db.query(`DROP INDEX "public"."IDX_7f50f702330bd90c3eb85bcbda"`)
    await db.query(`DROP INDEX "public"."IDX_4832b065968736dc04d37ca5da"`)
    await db.query(`DROP INDEX "public"."IDX_7bdd91da49e79f51ebd8fb774c"`)
    await db.query(`DROP INDEX "public"."IDX_30e9455c5aa944326797150a1b"`)
    await db.query(`DROP INDEX "public"."IDX_6b15368424e1f5cf587c2f3c5a"`)
    await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_f1f1143749d9fd473890b77054b"`)
    await db.query(`ALTER TABLE "parachain" DROP CONSTRAINT "FK_115c699f0d08e6a3eb40e7b085a"`)
    await db.query(`ALTER TABLE "crowdloan" DROP CONSTRAINT "FK_7ecfe931e23f88d1e45d5f658f1"`)
    await db.query(`ALTER TABLE "contribution" DROP CONSTRAINT "FK_7f50f702330bd90c3eb85bcbda5"`)
    await db.query(`ALTER TABLE "reward" DROP CONSTRAINT "FK_4832b065968736dc04d37ca5daf"`)
    await db.query(`ALTER TABLE "slash" DROP CONSTRAINT "FK_7bdd91da49e79f51ebd8fb774cb"`)
    await db.query(`ALTER TABLE "stake" DROP CONSTRAINT "FK_30e9455c5aa944326797150a1bb"`)
    await db.query(`ALTER TABLE "account" DROP CONSTRAINT "FK_6b15368424e1f5cf587c2f3c5ac"`)
  }
}
