module.exports = class Data1661517589689 {
  name = 'Data1661517589689'

  async up(db) {
    await db.query(`ALTER TABLE "account_transfer" DROP CONSTRAINT "FK_d5240d17696e229585da974641a"`)
    await db.query(`ALTER TABLE "account_transfer" ALTER COLUMN "account_id" DROP NOT NULL`)
    await db.query(`ALTER TABLE "contribution" DROP CONSTRAINT "FK_34a9b7747fbe547737724da5a3b"`)
    await db.query(`ALTER TABLE "contribution" DROP CONSTRAINT "FK_1e238c006392e74f87e2db5bf9b"`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "crowdloan_id" DROP NOT NULL`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "account_id" DROP NOT NULL`)
    await db.query(`ALTER TABLE "era_nomination" DROP CONSTRAINT "FK_8d0f2c79f04ed0571d6d8f3f1c5"`)
    await db.query(`ALTER TABLE "era_nomination" ALTER COLUMN "era_id" DROP NOT NULL`)
    await db.query(`ALTER TABLE "era_staker" DROP CONSTRAINT "FK_73f758807f518c1dbd30b6a76d9"`)
    await db.query(`ALTER TABLE "era_staker" ALTER COLUMN "era_id" DROP NOT NULL`)
    await db.query(`ALTER TABLE "rmrk_emote" DROP CONSTRAINT "FK_07e5f21332829c7f641cad73abd"`)
    await db.query(`ALTER TABLE "rmrk_emote" DROP CONSTRAINT "FK_575e604716561ae203764120d73"`)
    await db.query(`ALTER TABLE "rmrk_emote" ALTER COLUMN "nft_id" DROP NOT NULL`)
    await db.query(`ALTER TABLE "rmrk_emote" ALTER COLUMN "caller_id" DROP NOT NULL`)
    await db.query(`ALTER TABLE "rmrk_nft" DROP CONSTRAINT "FK_577ee6446dbef8991a651de12ed"`)
    await db.query(`ALTER TABLE "rmrk_nft" ALTER COLUMN "collection_id" DROP NOT NULL`)
    await db.query(`ALTER TABLE "rmrk_collection" ALTER COLUMN "issuer" SET NOT NULL`)
    await db.query(`ALTER TABLE "account_transfer" ADD CONSTRAINT "FK_d5240d17696e229585da974641a" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "contribution" ADD CONSTRAINT "FK_34a9b7747fbe547737724da5a3b" FOREIGN KEY ("crowdloan_id") REFERENCES "crowdloan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "contribution" ADD CONSTRAINT "FK_1e238c006392e74f87e2db5bf9b" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "era_nomination" ADD CONSTRAINT "FK_8d0f2c79f04ed0571d6d8f3f1c5" FOREIGN KEY ("era_id") REFERENCES "era"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "era_staker" ADD CONSTRAINT "FK_73f758807f518c1dbd30b6a76d9" FOREIGN KEY ("era_id") REFERENCES "era"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "rmrk_emote" ADD CONSTRAINT "FK_07e5f21332829c7f641cad73abd" FOREIGN KEY ("nft_id") REFERENCES "rmrk_nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "rmrk_emote" ADD CONSTRAINT "FK_575e604716561ae203764120d73" FOREIGN KEY ("caller_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "rmrk_nft" ADD CONSTRAINT "FK_577ee6446dbef8991a651de12ed" FOREIGN KEY ("collection_id") REFERENCES "rmrk_collection"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
  }

  async down(db) {
    await db.query(`ALTER TABLE "account_transfer" ADD CONSTRAINT "FK_d5240d17696e229585da974641a" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "account_transfer" ALTER COLUMN "account_id" SET NOT NULL`)
    await db.query(`ALTER TABLE "contribution" ADD CONSTRAINT "FK_34a9b7747fbe547737724da5a3b" FOREIGN KEY ("crowdloan_id") REFERENCES "crowdloan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "contribution" ADD CONSTRAINT "FK_1e238c006392e74f87e2db5bf9b" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "crowdloan_id" SET NOT NULL`)
    await db.query(`ALTER TABLE "contribution" ALTER COLUMN "account_id" SET NOT NULL`)
    await db.query(`ALTER TABLE "era_nomination" ADD CONSTRAINT "FK_8d0f2c79f04ed0571d6d8f3f1c5" FOREIGN KEY ("era_id") REFERENCES "era"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "era_nomination" ALTER COLUMN "era_id" SET NOT NULL`)
    await db.query(`ALTER TABLE "era_staker" ADD CONSTRAINT "FK_73f758807f518c1dbd30b6a76d9" FOREIGN KEY ("era_id") REFERENCES "era"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "era_staker" ALTER COLUMN "era_id" SET NOT NULL`)
    await db.query(`ALTER TABLE "rmrk_emote" ADD CONSTRAINT "FK_07e5f21332829c7f641cad73abd" FOREIGN KEY ("nft_id") REFERENCES "rmrk_nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "rmrk_emote" ADD CONSTRAINT "FK_575e604716561ae203764120d73" FOREIGN KEY ("caller_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "rmrk_emote" ALTER COLUMN "nft_id" SET NOT NULL`)
    await db.query(`ALTER TABLE "rmrk_emote" ALTER COLUMN "caller_id" SET NOT NULL`)
    await db.query(`ALTER TABLE "rmrk_nft" ADD CONSTRAINT "FK_577ee6446dbef8991a651de12ed" FOREIGN KEY ("collection_id") REFERENCES "rmrk_collection"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "rmrk_nft" ALTER COLUMN "collection_id" SET NOT NULL`)
    await db.query(`ALTER TABLE "rmrk_collection" ALTER COLUMN "issuer" DROP NOT NULL`)
    await db.query(`ALTER TABLE "account_transfer" DROP CONSTRAINT "FK_d5240d17696e229585da974641a"`)
    await db.query(`ALTER TABLE "contribution" DROP CONSTRAINT "FK_34a9b7747fbe547737724da5a3b"`)
    await db.query(`ALTER TABLE "contribution" DROP CONSTRAINT "FK_1e238c006392e74f87e2db5bf9b"`)
    await db.query(`ALTER TABLE "era_nomination" DROP CONSTRAINT "FK_8d0f2c79f04ed0571d6d8f3f1c5"`)
    await db.query(`ALTER TABLE "era_staker" DROP CONSTRAINT "FK_73f758807f518c1dbd30b6a76d9"`)
    await db.query(`ALTER TABLE "rmrk_emote" DROP CONSTRAINT "FK_07e5f21332829c7f641cad73abd"`)
    await db.query(`ALTER TABLE "rmrk_emote" DROP CONSTRAINT "FK_575e604716561ae203764120d73"`)
    await db.query(`ALTER TABLE "rmrk_nft" DROP CONSTRAINT "FK_577ee6446dbef8991a651de12ed"`)
  }
}
