module.exports = class Data1674053123846 {
    name = 'Data1674053123846'

    async up(db) {
        await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496"`)
        await db.query(`ALTER TABLE "transfer" ALTER COLUMN "from_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "account_transfer" DROP CONSTRAINT "FK_d5240d17696e229585da974641a"`)
        await db.query(`ALTER TABLE "account_transfer" ALTER COLUMN "account_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "era_staker" DROP CONSTRAINT "FK_db3082693cd9861527d1ab01856"`)
        await db.query(`ALTER TABLE "era_staker" ALTER COLUMN "staker_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "slash" DROP CONSTRAINT "FK_11c194818d549fdd45eb5f4cbf4"`)
        await db.query(`ALTER TABLE "slash" DROP CONSTRAINT "FK_6c2fff31390875a548de9d820d8"`)
        await db.query(`ALTER TABLE "slash" ALTER COLUMN "account_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "slash" ALTER COLUMN "staker_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "bond" DROP CONSTRAINT "FK_380e0ca8c041bf10c97b66b184b"`)
        await db.query(`ALTER TABLE "bond" DROP CONSTRAINT "FK_6840433bfd0de70586c3d8f333d"`)
        await db.query(`ALTER TABLE "bond" ALTER COLUMN "account_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "bond" ALTER COLUMN "staker_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "staker" DROP CONSTRAINT "FK_15b7e74748f940d0ccfbf21f1c0"`)
        await db.query(`ALTER TABLE "staker" ALTER COLUMN "controller_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "reward" DROP CONSTRAINT "FK_d244ddc409b7278fcd1e8e54da5"`)
        await db.query(`ALTER TABLE "reward" ALTER COLUMN "staker_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496" FOREIGN KEY ("from_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "account_transfer" ADD CONSTRAINT "FK_d5240d17696e229585da974641a" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "era_staker" ADD CONSTRAINT "FK_db3082693cd9861527d1ab01856" FOREIGN KEY ("staker_id") REFERENCES "staker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "slash" ADD CONSTRAINT "FK_11c194818d549fdd45eb5f4cbf4" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "slash" ADD CONSTRAINT "FK_6c2fff31390875a548de9d820d8" FOREIGN KEY ("staker_id") REFERENCES "staker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "bond" ADD CONSTRAINT "FK_380e0ca8c041bf10c97b66b184b" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "bond" ADD CONSTRAINT "FK_6840433bfd0de70586c3d8f333d" FOREIGN KEY ("staker_id") REFERENCES "staker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "staker" ADD CONSTRAINT "FK_15b7e74748f940d0ccfbf21f1c0" FOREIGN KEY ("controller_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "reward" ADD CONSTRAINT "FK_d244ddc409b7278fcd1e8e54da5" FOREIGN KEY ("staker_id") REFERENCES "staker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496" FOREIGN KEY ("from_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "transfer" ALTER COLUMN "from_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "account_transfer" ADD CONSTRAINT "FK_d5240d17696e229585da974641a" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "account_transfer" ALTER COLUMN "account_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "era_staker" ADD CONSTRAINT "FK_db3082693cd9861527d1ab01856" FOREIGN KEY ("staker_id") REFERENCES "staker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "era_staker" ALTER COLUMN "staker_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "slash" ADD CONSTRAINT "FK_11c194818d549fdd45eb5f4cbf4" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "slash" ADD CONSTRAINT "FK_6c2fff31390875a548de9d820d8" FOREIGN KEY ("staker_id") REFERENCES "staker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "slash" ALTER COLUMN "account_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "slash" ALTER COLUMN "staker_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "bond" ADD CONSTRAINT "FK_380e0ca8c041bf10c97b66b184b" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "bond" ADD CONSTRAINT "FK_6840433bfd0de70586c3d8f333d" FOREIGN KEY ("staker_id") REFERENCES "staker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "bond" ALTER COLUMN "account_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "bond" ALTER COLUMN "staker_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "staker" ADD CONSTRAINT "FK_15b7e74748f940d0ccfbf21f1c0" FOREIGN KEY ("controller_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "staker" ALTER COLUMN "controller_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "reward" ADD CONSTRAINT "FK_d244ddc409b7278fcd1e8e54da5" FOREIGN KEY ("staker_id") REFERENCES "staker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "reward" ALTER COLUMN "staker_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496"`)
        await db.query(`ALTER TABLE "account_transfer" DROP CONSTRAINT "FK_d5240d17696e229585da974641a"`)
        await db.query(`ALTER TABLE "era_staker" DROP CONSTRAINT "FK_db3082693cd9861527d1ab01856"`)
        await db.query(`ALTER TABLE "slash" DROP CONSTRAINT "FK_11c194818d549fdd45eb5f4cbf4"`)
        await db.query(`ALTER TABLE "slash" DROP CONSTRAINT "FK_6c2fff31390875a548de9d820d8"`)
        await db.query(`ALTER TABLE "bond" DROP CONSTRAINT "FK_380e0ca8c041bf10c97b66b184b"`)
        await db.query(`ALTER TABLE "bond" DROP CONSTRAINT "FK_6840433bfd0de70586c3d8f333d"`)
        await db.query(`ALTER TABLE "staker" DROP CONSTRAINT "FK_15b7e74748f940d0ccfbf21f1c0"`)
        await db.query(`ALTER TABLE "reward" DROP CONSTRAINT "FK_d244ddc409b7278fcd1e8e54da5"`)
    }
}
