module.exports = class Data1674045347191 {
    name = 'Data1674045347191'

    async up(db) {
        await db.query(`DROP INDEX "public"."IDX_046c23d020b95c1f8a3a2f28c5"`)
        await db.query(`DROP INDEX "public"."IDX_0bd97db4e1e32b00a831351680"`)
        await db.query(`DROP INDEX "public"."IDX_b1c227ef81daeda29c93409abe"`)
        await db.query(`ALTER TABLE "account" RENAME COLUMN "last_update_block" TO "synced_at"`)
        await db.query(`ALTER TABLE "transfer" DROP COLUMN "to"`)
        await db.query(`ALTER TABLE "transfer" DROP COLUMN "from"`)
        await db.query(`ALTER TABLE "transfer" DROP COLUMN "asset"`)
        await db.query(`ALTER TABLE "transfer" DROP COLUMN "type"`)
        await db.query(`ALTER TABLE "parachain" DROP COLUMN "para_id"`)
        await db.query(`ALTER TABLE "crowdloan" DROP COLUMN "end"`)
        await db.query(`ALTER TABLE "crowdloan" DROP COLUMN "start"`)
        await db.query(`ALTER TABLE "bond" DROP COLUMN "success"`)
        await db.query(`ALTER TABLE "staker" DROP COLUMN "commission"`)
        await db.query(`ALTER TABLE "reward" DROP COLUMN "validator"`)
        await db.query(`ALTER TABLE "reward" DROP COLUMN "call_id"`)
        await db.query(`ALTER TABLE "transfer" ADD "from_id" character varying NOT NULL`)
        await db.query(`ALTER TABLE "transfer" ADD "to_id" character varying`)
        await db.query(`ALTER TABLE "transfer" ADD "amount" numeric NOT NULL`)
        await db.query(`ALTER TABLE "crowdloan" ADD "created_at_timestamp" TIMESTAMP WITH TIME ZONE`)
        await db.query(`ALTER TABLE "crowdloan" ADD "ended_at" integer`)
        await db.query(`ALTER TABLE "crowdloan" ADD "ended_at_timestamp" TIMESTAMP WITH TIME ZONE`)
        await db.query(`ALTER TABLE "crowdloan" ADD "status" character varying(9) NOT NULL`)
        await db.query(`ALTER TABLE "reward" ADD "validator_id" text`)
        await db.query(`ALTER TABLE "transfer" ALTER COLUMN "extrinsic_hash" DROP NOT NULL`)
        await db.query(`ALTER TABLE "account_transfer" DROP CONSTRAINT "FK_d5240d17696e229585da974641a"`)
        await db.query(`ALTER TABLE "account_transfer" ALTER COLUMN "account_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "crowdloan" DROP CONSTRAINT "FK_005883fcd4519fa5ae88706b3a5"`)
        await db.query(`ALTER TABLE "crowdloan" DROP COLUMN "created_at"`)
        await db.query(`ALTER TABLE "crowdloan" ADD "created_at" integer`)
        await db.query(`ALTER TABLE "crowdloan" ALTER COLUMN "parachain_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "contribution" DROP CONSTRAINT "FK_1e238c006392e74f87e2db5bf9b"`)
        await db.query(`ALTER TABLE "contribution" ALTER COLUMN "account_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "slash" DROP CONSTRAINT "FK_6c2fff31390875a548de9d820d8"`)
        await db.query(`ALTER TABLE "slash" ALTER COLUMN "amount" SET NOT NULL`)
        await db.query(`ALTER TABLE "slash" ALTER COLUMN "staker_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "bond" DROP CONSTRAINT "FK_6840433bfd0de70586c3d8f333d"`)
        await db.query(`ALTER TABLE "bond" ALTER COLUMN "staker_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "staker" DROP CONSTRAINT "FK_1df4573c718e95292cd00f49c35"`)
        await db.query(`ALTER TABLE "staker" ALTER COLUMN "payee_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "reward" DROP CONSTRAINT "FK_4a8843fdb7840bfd00f8e4f7b36"`)
        await db.query(`ALTER TABLE "reward" DROP CONSTRAINT "FK_d244ddc409b7278fcd1e8e54da5"`)
        await db.query(`ALTER TABLE "reward" ALTER COLUMN "account_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "reward" ALTER COLUMN "amount" SET NOT NULL`)
        await db.query(`ALTER TABLE "reward" ALTER COLUMN "staker_id" SET NOT NULL`)
        await db.query(`CREATE INDEX "IDX_70ff8b624c3118ac3a4862d22c" ON "transfer" ("timestamp") `)
        await db.query(`CREATE INDEX "IDX_76bdfed1a7eb27c6d8ecbb7349" ON "transfer" ("from_id") `)
        await db.query(`CREATE INDEX "IDX_0751309c66e97eac9ef1149362" ON "transfer" ("to_id") `)
        await db.query(`CREATE INDEX "IDX_f4007436c1b546ede08a4fd7ab" ON "transfer" ("amount") `)
        await db.query(`CREATE INDEX "IDX_e132a7de99aecaa867d4e3a273" ON "crowdloan" ("ended_at") `)
        await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496" FOREIGN KEY ("from_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_0751309c66e97eac9ef11493623" FOREIGN KEY ("to_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "account_transfer" ADD CONSTRAINT "FK_d5240d17696e229585da974641a" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "crowdloan" ADD CONSTRAINT "FK_005883fcd4519fa5ae88706b3a5" FOREIGN KEY ("parachain_id") REFERENCES "parachain"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "contribution" ADD CONSTRAINT "FK_1e238c006392e74f87e2db5bf9b" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "slash" ADD CONSTRAINT "FK_6c2fff31390875a548de9d820d8" FOREIGN KEY ("staker_id") REFERENCES "staker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "bond" ADD CONSTRAINT "FK_6840433bfd0de70586c3d8f333d" FOREIGN KEY ("staker_id") REFERENCES "staker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "staker" ADD CONSTRAINT "FK_1df4573c718e95292cd00f49c35" FOREIGN KEY ("payee_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "reward" ADD CONSTRAINT "FK_4a8843fdb7840bfd00f8e4f7b36" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "reward" ADD CONSTRAINT "FK_d244ddc409b7278fcd1e8e54da5" FOREIGN KEY ("staker_id") REFERENCES "staker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`CREATE INDEX "IDX_046c23d020b95c1f8a3a2f28c5" ON "crowdloan" ("start") `)
        await db.query(`CREATE INDEX "IDX_0bd97db4e1e32b00a831351680" ON "bond" ("success") `)
        await db.query(`CREATE INDEX "IDX_b1c227ef81daeda29c93409abe" ON "reward" ("call_id") `)
        await db.query(`ALTER TABLE "account" RENAME COLUMN "synced_at" TO "last_update_block"`)
        await db.query(`ALTER TABLE "transfer" ADD "to" jsonb`)
        await db.query(`ALTER TABLE "transfer" ADD "from" jsonb NOT NULL`)
        await db.query(`ALTER TABLE "transfer" ADD "asset" jsonb NOT NULL`)
        await db.query(`ALTER TABLE "transfer" ADD "type" character varying(12) NOT NULL`)
        await db.query(`ALTER TABLE "parachain" ADD "para_id" integer`)
        await db.query(`ALTER TABLE "crowdloan" ADD "end" integer NOT NULL`)
        await db.query(`ALTER TABLE "crowdloan" ADD "start" integer`)
        await db.query(`ALTER TABLE "bond" ADD "success" boolean`)
        await db.query(`ALTER TABLE "staker" ADD "commission" integer`)
        await db.query(`ALTER TABLE "reward" ADD "validator" text`)
        await db.query(`ALTER TABLE "reward" ADD "call_id" text`)
        await db.query(`ALTER TABLE "transfer" DROP COLUMN "from_id"`)
        await db.query(`ALTER TABLE "transfer" DROP COLUMN "to_id"`)
        await db.query(`ALTER TABLE "transfer" DROP COLUMN "amount"`)
        await db.query(`ALTER TABLE "crowdloan" DROP COLUMN "created_at_timestamp"`)
        await db.query(`ALTER TABLE "crowdloan" DROP COLUMN "ended_at"`)
        await db.query(`ALTER TABLE "crowdloan" DROP COLUMN "ended_at_timestamp"`)
        await db.query(`ALTER TABLE "crowdloan" DROP COLUMN "status"`)
        await db.query(`ALTER TABLE "reward" DROP COLUMN "validator_id"`)
        await db.query(`ALTER TABLE "transfer" ALTER COLUMN "extrinsic_hash" SET NOT NULL`)
        await db.query(`ALTER TABLE "account_transfer" ADD CONSTRAINT "FK_d5240d17696e229585da974641a" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "account_transfer" ALTER COLUMN "account_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "crowdloan" ADD CONSTRAINT "FK_005883fcd4519fa5ae88706b3a5" FOREIGN KEY ("parachain_id") REFERENCES "parachain"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "crowdloan" ADD "created_at" TIMESTAMP WITH TIME ZONE`)
        await db.query(`ALTER TABLE "crowdloan" DROP COLUMN "created_at"`)
        await db.query(`ALTER TABLE "crowdloan" ALTER COLUMN "parachain_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "contribution" ADD CONSTRAINT "FK_1e238c006392e74f87e2db5bf9b" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "contribution" ALTER COLUMN "account_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "slash" ADD CONSTRAINT "FK_6c2fff31390875a548de9d820d8" FOREIGN KEY ("staker_id") REFERENCES "staker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "slash" ALTER COLUMN "amount" DROP NOT NULL`)
        await db.query(`ALTER TABLE "slash" ALTER COLUMN "staker_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "bond" ADD CONSTRAINT "FK_6840433bfd0de70586c3d8f333d" FOREIGN KEY ("staker_id") REFERENCES "staker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "bond" ALTER COLUMN "staker_id" DROP NOT NULL`)
        await db.query(`ALTER TABLE "staker" ADD CONSTRAINT "FK_1df4573c718e95292cd00f49c35" FOREIGN KEY ("payee_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "staker" ALTER COLUMN "payee_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "reward" ADD CONSTRAINT "FK_4a8843fdb7840bfd00f8e4f7b36" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "reward" ADD CONSTRAINT "FK_d244ddc409b7278fcd1e8e54da5" FOREIGN KEY ("staker_id") REFERENCES "staker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "reward" ALTER COLUMN "account_id" SET NOT NULL`)
        await db.query(`ALTER TABLE "reward" ALTER COLUMN "amount" DROP NOT NULL`)
        await db.query(`ALTER TABLE "reward" ALTER COLUMN "staker_id" DROP NOT NULL`)
        await db.query(`DROP INDEX "public"."IDX_70ff8b624c3118ac3a4862d22c"`)
        await db.query(`DROP INDEX "public"."IDX_76bdfed1a7eb27c6d8ecbb7349"`)
        await db.query(`DROP INDEX "public"."IDX_0751309c66e97eac9ef1149362"`)
        await db.query(`DROP INDEX "public"."IDX_f4007436c1b546ede08a4fd7ab"`)
        await db.query(`DROP INDEX "public"."IDX_e132a7de99aecaa867d4e3a273"`)
        await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496"`)
        await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_0751309c66e97eac9ef11493623"`)
        await db.query(`ALTER TABLE "account_transfer" DROP CONSTRAINT "FK_d5240d17696e229585da974641a"`)
        await db.query(`ALTER TABLE "crowdloan" DROP CONSTRAINT "FK_005883fcd4519fa5ae88706b3a5"`)
        await db.query(`ALTER TABLE "contribution" DROP CONSTRAINT "FK_1e238c006392e74f87e2db5bf9b"`)
        await db.query(`ALTER TABLE "slash" DROP CONSTRAINT "FK_6c2fff31390875a548de9d820d8"`)
        await db.query(`ALTER TABLE "bond" DROP CONSTRAINT "FK_6840433bfd0de70586c3d8f333d"`)
        await db.query(`ALTER TABLE "staker" DROP CONSTRAINT "FK_1df4573c718e95292cd00f49c35"`)
        await db.query(`ALTER TABLE "reward" DROP CONSTRAINT "FK_4a8843fdb7840bfd00f8e4f7b36"`)
        await db.query(`ALTER TABLE "reward" DROP CONSTRAINT "FK_d244ddc409b7278fcd1e8e54da5"`)
    }
}
