const chains = [
    {
        id: 'polkadot',
        token: 'DOT',
        decimals: 10,
        paraId: null,
        relay: 'polkadot',
    },
    {
        id: 'acala',
        token: 'ACA',
        decimals: 12,
        paraId: 2000,
        relay: 'polkadot',
    },
    {
        id: 'ares',
        token: 'AMAS',
        decimals: 12,
        paraId: 2028,
        relay: 'polkadot',
    },
    {
        id: 'astar',
        token: 'ASTR',
        decimals: 18,
        paraId: 2006,
        relay: 'polkadot',
    },
    {
        id: 'centrifuge',
        token: 'CFG',
        decimals: 18,
        paraId: 2031,
        relay: 'polkadot',
    },
    {
        id: 'clover',
        token: 'CLV',
        decimals: 18,
        paraId: 2002,
        relay: 'polkadot',
    },
    {
        id: 'coinversation',
        token: 'CTO',
        decimals: null,
        paraId: 2027,
        relay: 'polkadot',
    },
    {
        id: 'composable-finance',
        token: 'LAYR',
        decimals: 12,
        paraId: 2019,
        relay: 'polkadot',
    },
    {
        id: 'crust',
        token: 'CRU',
        decimals: 12,
        paraId: 2008,
        relay: 'polkadot',
    },
    {
        id: 'darwinia',
        token: 'RING',
        decimals: 9,
        paraId: 2003,
        relay: 'polkadot',
    },
    {
        id: 'efinity',
        token: 'EFI',
        decimals: 18,
        paraId: 2021,
        relay: 'polkadot',
    },
    {
        id: 'equilibrium',
        token: 'Unknown',
        decimals: 9,
        paraId: 2011,
        relay: 'polkadot',
    },
    {
        id: 'hydradx',
        token: 'HDX',
        decimals: 12,
        paraId: 2034,
        relay: 'polkadot',
    },
    {
        id: 'interlay',
        token: 'INTR',
        decimals: 10,
        paraId: 2032,
        relay: 'polkadot',
    },
    {
        id: 'litentry',
        token: 'LIT',
        decimals: 12,
        paraId: 2013,
        relay: 'polkadot',
    },
    {
        id: 'manta',
        token: 'MANTA',
        decimals: 18,
        paraId: 2015,
        relay: 'polkadot',
    },
    {
        id: 'moonbeam',
        token: 'GLMR',
        decimals: 18,
        paraId: 2004,
        relay: 'polkadot',
    },
    {
        id: 'nodle',
        token: 'NODL',
        decimals: 18,
        paraId: 2026,
        relay: 'polkadot',
    },
    {
        id: 'parallel',
        token: 'PARA',
        decimals: 12,
        paraId: 2012,
        relay: 'polkadot',
    },
    {
        id: 'phala',
        token: 'PHA',
        decimals: 12,
        paraId: 2035,
        relay: 'polkadot',
    },
    {
        id: 'polkadex',
        token: 'PDEX',
        decimals: 12,
        paraId: 2036,
        relay: 'polkadot',
    },
    {
        id: 'statemint',
        token: 'DOT',
        decimals: 10,
        paraId: 1000,
        relay: 'polkadot',
    },
    {
        id: 'subdao',
        token: 'GOV',
        decimals: 12,
        paraId: 2018,
        relay: 'polkadot',
    },
    {
        id: 'subgame',
        token: 'GSGB',
        decimals: 10,
        paraId: 2017,
        relay: 'polkadot',
    },
    {
        id: 'kusama',
        token: 'KSM',
        decimals: 12,
        paraId: null,
        relay: 'kusama',
    },
    {
        id: 'altair',
        token: 'AIR',
        decimals: 18,
        paraId: 2088,
        relay: 'kusama',
    },
    {
        id: 'basilisk',
        token: 'BSX',
        decimals: 12,
        paraId: 2090,
        relay: 'kusama',
    },
    {
        id: 'bifrost-ksm',
        token: 'BNC',
        decimals: 12,
        paraId: 2001,
        relay: 'kusama',
    },
    {
        id: 'bit-country-pioneer',
        token: 'NEER',
        decimals: 18,
        paraId: 2096,
        relay: 'kusama',
    },
    {
        id: 'calamari',
        token: 'KMA',
        decimals: 12,
        paraId: 2084,
        relay: 'kusama',
    },
    {
        id: 'crust-shadow',
        token: 'CSM',
        decimals: 12,
        paraId: 2012,
        relay: 'kusama',
    },
    {
        id: 'darwinia-crab',
        token: 'CRAB',
        decimals: 9,
        paraId: 2105,
        relay: 'kusama',
    },
    {
        id: 'darwinia-crab-redirect',
        token: 'CRING',
        decimals: 9,
        paraId: 2006,
        relay: 'kusama',
    },
    {
        id: 'encointer',
        token: 'KSM',
        decimals: 12,
        paraId: 1001,
        relay: 'kusama',
    },
    {
        id: 'genshiro',
        token: 'TOKEN',
        decimals: 9,
        paraId: 2024,
        relay: 'kusama',
    },
    {
        id: 'integritee',
        token: 'TEER',
        decimals: 12,
        paraId: 2015,
        relay: 'kusama',
    },
    {
        id: 'karura',
        token: 'KAR',
        decimals: 12,
        paraId: 2000,
        relay: 'kusama',
    },
    {
        id: 'khala',
        token: 'PHA',
        decimals: 12,
        paraId: 2004,
        relay: 'kusama',
    },
    {
        id: 'kico',
        token: 'KICO',
        decimals: 14,
        paraId: 2107,
        relay: 'kusama',
    },
    {
        id: 'kilt-spiritnet',
        token: 'KILT',
        decimals: 15,
        paraId: 2086,
        relay: 'kusama',
    },
    {
        id: 'kintsugi-btc',
        token: 'KINT',
        decimals: 12,
        paraId: 2092,
        relay: 'kusama',
    },
    {
        id: 'kpron',
        token: 'KPN',
        decimals: 12,
        paraId: 2019,
        relay: 'kusama',
    },
    {
        id: 'litmus',
        token: 'LIT',
        decimals: 12,
        paraId: 2106,
        relay: 'kusama',
    },
    {
        id: 'loom',
        token: 'LOOM',
        decimals: null,
        paraId: 2080,
        relay: 'kusama',
    },
    {
        id: 'mars',
        token: 'AMAS',
        decimals: 12,
        paraId: 2008,
        relay: 'kusama',
    },
    {
        id: 'moonriver',
        token: 'MOVR',
        decimals: 18,
        paraId: 2023,
        relay: 'kusama',
    },
    {
        id: 'parallel-heiko',
        token: 'HKO',
        decimals: 12,
        paraId: 2085,
        relay: 'kusama',
    },
    {
        id: 'picasso',
        token: 'PICA',
        decimals: 12,
        paraId: 2087,
        relay: 'kusama',
    },
    {
        id: 'pichiu',
        token: 'PCHU',
        decimals: null,
        paraId: 2102,
        relay: 'kusama',
    },
    {
        id: 'polkasmith',
        token: 'PKS',
        decimals: 18,
        paraId: 2009,
        relay: 'kusama',
    },
    {
        id: 'quartz',
        token: 'QTZ',
        decimals: 18,
        paraId: 2095,
        relay: 'kusama',
    },
    {
        id: 'robonomics',
        token: 'XRT',
        decimals: 9,
        paraId: 2048,
        relay: 'kusama',
    },
    {
        id: 'sakura',
        token: 'SKU',
        decimals: null,
        paraId: 2016,
        relay: 'kusama',
    },
    {
        id: 'sherpax',
        token: 'KSX',
        decimals: null,
        paraId: 2013,
        relay: 'kusama',
    },
    {
        id: 'shiden',
        token: 'SDN',
        decimals: 18,
        paraId: 2007,
        relay: 'kusama',
    },
    {
        id: 'sora-kusama',
        token: 'XOR',
        decimals: null,
        paraId: 2011,
        relay: 'kusama',
    },
    {
        id: 'statemine',
        token: 'KSM',
        decimals: 12,
        paraId: 1000,
        relay: 'kusama',
    },
    {
        id: 'subgame-gamma',
        token: 'GSGB',
        decimals: 10,
        paraId: 2018,
        relay: 'kusama',
    },
    {
        id: 'subsocialx',
        token: 'SUB',
        decimals: 11,
        paraId: 2100,
        relay: 'kusama',
    },
    {
        id: 'unorthodox',
        token: 'STND',
        decimals: 15,
        paraId: 2094,
        relay: 'kusama',
    },
    {
        id: 'zeitgeist',
        token: 'ZTG',
        decimals: 10,
        paraId: 2101,
        relay: 'kusama',
    },
] as const

export default chains
