export const nativeTokens: Map<string, { symbol: string; decimals: number }> = new Map()
    .set('ACA', { symbol: 'ACA', decimals: 12 })
    .set('AUSD', { symbol: 'AUSD', decimals: 12 })
    .set('DOT', { symbol: 'DOT', decimals: 10 })
    .set('LDOT', { symbol: 'LDOT', decimals: 10 })
    .set('RENBTC', { symbol: 'RENBTC', decimals: 8 })
    .set('CASH', { symbol: 'CASH', decimals: 8 })
    .set('KAR', { symbol: 'KAR', decimals: 12 })
    .set('KUSD', { symbol: 'KUSD', decimals: 12 })
    .set('KSM', { symbol: 'KSM', decimals: 12 })
    .set('LKSM', { symbol: 'LKSM', decimals: 12 })
    .set('TAI', { symbol: 'TAI', decimals: 12 })
    .set('BNC', { symbol: 'BNC', decimals: 12 })
    .set('VSKSM', { symbol: 'VSKSM', decimals: 12 })
    .set('PHA', { symbol: 'PHA', decimals: 12 })
    .set('KINT', { symbol: 'KINT', decimals: 12 })
    .set('KBTC', { symbol: 'KBTC', decimals: 8 })
