export const nativeTokens: Map<string, [symbol: string, decimals: number]> = new Map()
    .set('ACA', ['ACA', 12])
    .set('AUSD', ['AUSD', 12])
    .set('DOT', ['DOT', 10])
    .set('LDOT', ['LDOT', 10])
    .set('RENBTC', ['RENBTC', 8])
    .set('CASH', ['CASH', 8])
    .set('KAR', ['KAR', 12])
    .set('KUSD', ['KUSD', 12])
    .set('KSM', ['KSM', 12])
    .set('LKSM', ['LKSM', 12])
    .set('TAI', ['TAI', 12])
    .set('BNC', ['BNC', 12])
    .set('VSKSM', ['VSKSM', 12])
    .set('PHA', ['PHA', 12])
    .set('KINT', ['KINT', 12])
    .set('KBTC', ['KBTC', 8])
